//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario2024.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public int ID_Venta { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> ID_Producto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> ID_Cliente { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
